# Optimized Docker Compose configuration using Bake-built images
# This configuration uses pre-built images from docker buildx bake

services:
  backend:
    image: local/cabinet-photo-backend:latest
    container_name: cabinet-photo-backend
    restart: unless-stopped
    user: "1000:1000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3001
    volumes:
      - ./data/uploads:/app/uploads
      - ./data/database:/app/database
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    image: local/kitchen-designer-frontend:latest
    container_name: kitchen-designer-frontend
    restart: unless-stopped
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  nginx-proxy:
    image: nginx:alpine
    container_name: kitchen-designer-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "3001:3001"
    volumes:
      - ./nginx-tunnel.conf:/etc/nginx/conf.d/default.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      frontend:
        condition: service_healthy
      backend:
        condition: service_healthy
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: kitchen-designer-certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  app-network:
    driver: bridge

volumes:
  uploads:
  database: