version: '3.8'

services:
  nginx-proxy:
    ports:
      - "8080:80"
      - "3001:3001"
    volumes:
      - ./nginx-tunnel.conf:/etc/nginx/conf.d/default.conf:ro

  backend:
    networks:
      - app-network

  frontend:
    environment:
      - REACT_APP_API_URL=https://api.gudinocustom.com
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
