# Docker Compose configuration for Zero-Downtime Deployments
# This file is used to spin up new service instances alongside existing ones

services:
  backend-new:
    build:
      context: ./cabinet-photo-server
      dockerfile: Dockerfile
    container_name: cabinet-photo-backend-new
    restart: unless-stopped
    user: "1000:1000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DEPLOY_MODE=true
    volumes:
      - ./data/uploads:/app/uploads
      - ./data/database:/app/database
    networks:
      - app-network
    # Use different port for new instance during deployment
    ports:
      - "3002:3001"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3001/api/health"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 60s

  frontend-new:
    build:
      context: ./kitchen-designer
      dockerfile: Dockerfile
    container_name: kitchen-designer-frontend-new
    restart: unless-stopped
    depends_on:
      backend-new:
        condition: service_healthy
    networks:
      - app-network
    # Use different port for new instance during deployment
    ports:
      - "8080:80"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 30s

networks:
  app-network:
    external: true

volumes:
  uploads:
    external: true
  database:
    external: true